### ISSUE TITLE
Card doesn't render properly when programatically setting card number etc.

### ISSUE THREAD

**Issue by biddster** [vinaygaba/CreditCardView#13]
I'm using the card view in a list. In the list adapter's getView, I findViewById for the credit card view and then I set card number, name and expiry. 

The following scenarios happen:

1. If the card isn't editable, nothing appears in the fields. 
2. If the card is editable, I can tap in the card number field and then my card number appears. 
3. If I remove the programmatic calls to setCardNumber etc and hardcode the number, name and expiry in the layout xml, the card renders correctly.

**Comment by vinaygaba** [comment]
Hi @biddster, could you please share your code, specifically the list adapter where u are setting up the views for me to troubleshoot the issue. Thanks.

**Comment by biddster** [comment]
I can't share that very easily due to the sensitive nature of the project, I'll knock up a test application that I can push to github for you.

**Comment by vinaygaba** [comment]
@biddster hey sure no problem. I'll set up something locally as well to test it out!

**Comment by biddster** [comment]
Here you go: https://github.com/biddster/CreditCardViewDemo

**Comment by heyharvs** [comment]
I can confirm, getting the same issue.  Using a List Fragment with BaseAdapter and viewholder pattern.  It correctly finds it, but none of the set() methods have any affect.

**Comment by vinaygaba** [comment]
Hi @biddster @heyharvs,
i have identified the fix and will be completing it in the next 1 hour. Will be putting it on maven soon after. Sending an update in a bit. Thank you for pointing this out.

**Comment by vinaygaba** [comment]
@biddster @heyharvs 
This was released just now as part of v1.0.3. So if you were already using the library (@bidster you were already using v1.0.3), you will have to delete the library(gradle\caches\modules-2\files-2.1\com.vinaygaba\creditcardview\1.0.3) and do the build again to get the latest version.

**Comment by biddster** [comment]
Thanks @vinaygaba, I'll test it. Is there any reason why you didn't bump the version number to 1.0.4? It's much easier for us all to be certain we're testing your fixed code that way.

**Comment by vinaygaba** [comment]
@biddster The reason I released this as part of v1.0.3 was because v1.0.3 was not "officially" released until today. I wanted to add more features as part of this release and hence I had not updated the documentation until today. Hence, I don't think anyone apart from you was using that version till now as even the Readme file showed v1.0.2 only.

**Comment by biddster** [comment]
Understood. I'm having read trouble getting the latest version. I've blown away my entire gradle cache directory and I'm still seeing the old code. I'm wondering if it's stuck in a maven proxy cache somewhere?

**Comment by vinaygaba** [comment]
Not sure @biddster . If you check the files here -https://oss.sonatype.org/content/groups/staging/com/vinaygaba/creditcardview/1.0.3/
you will see that the files have been updated today. Do you see v1.0.3 in your cache directory once it was downloaded again?

**Comment by biddster** [comment]
Yeah - the aar has been cache on the intertubes somewhere I think. 

I delete my gradle cache directory and the aar that gets downloaded is 1,271,325 bytes.

Your new version is 1,271,636.

I suspect that it's cached somewhere as you generally don't generally update versions you've already uploaded.

**Comment by vinaygaba** [comment]
@biddster Really sorry about that. Did you try the clean --> build cycle? Or could you download the aar and jar files and replace it in the cache? Never tried it but worth a shot. Before you do this, **plz take a back up** though as it does match the signatures so its possible it might fail.

**Comment by vinaygaba** [comment]
@biddster Do let me know if you are able to fix the cache issue. Henceforth, I will be more careful about the releases. Sorry about this!

**Comment by biddster** [comment]
Oh don't worry - we'll get to the bottom of it. The bigger worry for me is that if it is really permanently cached, other consumers will suffer the same problem as me as it's already too late.

**Comment by biddster** [comment]
I suspect snapshot releases are the way to go in the future:

https://discuss.gradle.org/t/how-to-get-gradle-to-download-newer-snapshots-to-gradle-cache-when-using-an-ivy-repository/7344

Then we can use the changing flag on the compile dependency.

**Comment by vinaygaba** [comment]
@biddster I'm going to read more about this and do releases in a more efficient manner. Sorry about the trouble I might have caused you.

**Comment by vinaygaba** [comment]
For this release in particular, can you try using this - https://jitpack.io/

**Comment by biddster** [comment]
Ok, it's working nicely via jitpack.io.

Add jitpack to all projects.
```
allprojects {
    repositories {
        maven { url "https://jitpack.io" }
    }
}
```

and then in your app gradle file

```
dependencies {
    compile(group: 'com.github.vinaygaba', name: 'CreditCardView', version: '1.0.3')
}
```

**Comment by biddster** [comment]
Confirming this bug as fixed.

**Comment by vinaygaba** [comment]
I had actually added a comment about jitpack but deleted it immediately as there are some new features that are still in dev that were commited to the repo. But looks like jitpack is smart enough to ppick binaries from the releases. Which is great!

**Comment by biddster** [comment]
Yes, it's working really well.

Many thanks again for the fixes.

**Comment by vinaygaba** [comment]
@biddster Thank you for pointing this out :+1:
